spring:
  application:
    name: student_service
  # postgresql
  datasource:
    url: jdbc:postgresql://localhost:5433/student_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
server:
  port: 8081
