services:
  student-services:
    container_name: docker-student-pg
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_db
    restart: unless-stopped

  courses-services:
    container_name: docker-courses-pg
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courses_db
    restart: unless-stopped

  courses-registration-service:
    container_name: docker-courses-registration-pg
    image: postgres:12
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courses_students_db
    restart: unless-stopped